# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: specs
description: > # this means to ignore newlines until "baseurl:"
  A bunch of ideas that you can use as practice for coding
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: nxtonic
github_username:  nxtonic

# Build settings
markdown: kramdown
